name: kitbase_analytics
description: Kitbase Analytics SDK for Dart and Flutter - Track events and logs in your application
version: 0.1.0
repository: https://github.com/scr2em/kitbase-sdk/tree/main/analytics/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  clock: ^1.1.2
  device_info_plus: ^11.3.0
  flutter:
    sdk: flutter
  http: ^1.2.0
  internet_connection_checker_plus: ^2.9.1+2
  package_info_plus: ^8.2.0
  path_provider: ^2.1.5
  sembast: ^3.7.4
  sembast_web: ^2.3.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  web: ^1.1.1


dev_dependencies:
  build_runner: ^2.4.13
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.24.0
