name: kitbase
description: Official Kitbase SDK for Dart/Flutter - Events tracking and changelogs
version: 0.1.0
repository: https://github.com/scr2em/kitbase-sdk/tree/main/packages/dart
homepage: https://kitbase.io

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  mockito: ^5.4.0
  build_runner: ^2.4.0


