name: kitbase_changelogs
description: Kitbase Changelogs SDK - Fetch version changelogs in your Dart/Flutter application
version: 0.1.0
repository: https://github.com/kitbase/kitbase-sdk/tree/main/packages/dart/changelogs
homepage: https://kitbase.io

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

