name: kitbase_changelogs
description: Kitbase Changelogs SDK for Dart and Flutter - Fetch version changelogs
version: 0.1.0
repository: https://github.com/scr2em/kitbase-sdk/tree/main/changelogs/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
